services:
  - type: web
    name: inventory-management-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false # This tells Render this is a secret that will be set manually
    healthCheckPath: /health
    autoDeploy: true
