services:
  - type: web
    name: inventory-management-api
    runtime: node
    plan: free
    region: ohio
    buildCommand: npm install && npm run swagger
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false # This will be set manually in the Render dashboard
    autoDeploy: true
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
